kind: wasmer.io/App.v0

name: manga-downloader

package: awminamani/manga-downloader

cli_args:
  - -m
  - flask
  - --app
  - app:app
  - run
  - --host=0.0.0.0
  - --port=8080

env:
  FLASK_APP: app:app
  PYTHONUNBUFFERED: "1"

locality:
  regions:
    - de-falkenstein
